spring.application.name=auth-service
server.port=8081
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# --- CONFIGURACIÓN ANTI-FIREWALL ---
# Forzamos a usar la IP numérica
eureka.instance.prefer-ip-address=true
# Y forzamos que esa IP sea SIEMPRE localhost
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=localhost