spring.application.name=auth-service
server.port=8081
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# --- CONFIGURACIÓN ANTI-FIREWALL ---
# Forzamos a usar la IP numérica
eureka.instance.prefer-ip-address=true
# Y forzamos que esa IP sea SIEMPRE localhost
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=localhost

# --- CONEXIÓN A LA BASE DE DATOS MARIADB ---
spring.datasource.url=jdbc:mariadb://localhost:3306/fivem_panel?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
# Pon tu contraseña de HeidiSQL aquí si tienes una. Si no tienes, déjalo en blanco.
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# --- CONFIGURACIÓN DE JPA ---
# 'update' es vital para NO borrar los datos de tu servidor de FiveM, solo añade lo que falte
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect