spring.application.name=auth-service
server.port=8081
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# --- CONFIGURACIÓN ANTI-FIREWALL ---
# Forzamos a usar la IP numérica
eureka.instance.prefer-ip-address=true
# Y forzamos que esa IP sea SIEMPRE localhost
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=localhost

# --- CONEXIÓN A LA BASE DE DATOS MARIADB ---
spring.datasource.url=jdbc:mariadb://localhost:3306/esxlegacy_c7c5a5?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
# Pon tu contraseña de HeidiSQL aquí si tienes una. Si no tienes, déjalo en blanco.
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# --- CONFIGURACIÓN DE JPA ---
# 'update' es vital para NO borrar los datos de tu servidor de FiveM, solo añade lo que falte
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# ==========================================
# CONFIGURACIÓN OAUTH2 DISCORD
# ==========================================
spring.security.oauth2.client.registration.discord.client-id= 1487451586753204295
spring.security.oauth2.client.registration.discord.client-secret=FnDYndGDnaTqQIvo_RzLwPWpTmIAHcjk
spring.security.oauth2.client.registration.discord.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.discord.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.discord.scope=identify,email
spring.security.oauth2.client.registration.discord.redirect-uri=http://localhost:8080/auth-service/login/oauth2/code/discord

# Endpoints oficiales de la API de Discord
spring.security.oauth2.client.provider.discord.authorization-uri=https://discord.com/api/oauth2/authorize
spring.security.oauth2.client.provider.discord.token-uri=https://discord.com/api/oauth2/token
spring.security.oauth2.client.provider.discord.user-info-uri=https://discord.com/api/users/@me
spring.security.oauth2.client.provider.discord.user-name-attribute=id