# Nombre del servicio
spring.application.name=api-gateway

# Puerto oficial de la web (El que usará Postman y React)
server.port=8080

# Conexión con Eureka (Le dice dónde está la guía telefónica)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Activar el descubrimiento automático de rutas
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true