spring.application.name=api-gateway
server.port=8080
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# --- CONFIGURACIÓN DE LA RUTA ---
# 1. ID único de la ruta
spring.cloud.gateway.routes[0].id=auth-service-route

# 2. A dónde lo mandamos (lb = Load Balancer -> Busca en Eureka)
# IMPORTANTE: Asegúrate de que en Eureka sale como AUTH-SERVICE (en mayúsculas suele ser mejor)
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE

# 3. Qué rutas capturamos (Todo lo que empiece por /auth-service/...)
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth-service/**

# 4. EL TRUCO MÁGICO: Quitar el primer trozo de la ruta (/auth-service)
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# --- RUTA PARA PLAYER-SERVICE ---
spring.cloud.gateway.routes[1].id=player-service-route
spring.cloud.gateway.routes[1].uri=lb://PLAYER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/player-service/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

# --- RUTA PARA MGMT-SERVICE ---
spring.cloud.gateway.routes[2].id=mgmt-service-route
spring.cloud.gateway.routes[2].uri=lb://MGMT-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/mgmt-service/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

# --- CONFIGURACIÓN ANTI-FIREWALL ---
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=localhost