spring.application.name=player-service
server.port=8082

# --- EUREKA ---
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=localhost

# --- CONEXIÓN A LA BASE DE DATOS MARIADB (misma BD que FiveM) ---
spring.datasource.url=jdbc:mariadb://localhost:3306/esxlegacy_c7c5a5?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# --- CONFIGURACIÓN DE JPA ---
# 'validate' comprueba que el molde (Player.java) coincide con la BD sin tocar nada
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
