# 1. Nombre del servicio (Importante para que se reconozcan entre ellos)
spring.application.name=eureka-server

# 2. El puerto oficial de Eureka es el 8761
server.port=8761

# 3. Configuración para que NO intente registrarse consigo mismo 
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false